language: go

go:
  - 1.10.x
  - 1.11.x

before_install:
  # Build tools
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign

  # Project dependencies
  - go get github.com/djherbis/times
  - go get github.com/mitchellh/go-homedir       
  - go get github.com/spf13/viper
  - go get github.com/theckman/go-flock
  - go get gopkg.in/gomail.v2

  # Duplicacy STUB
  - sudo touch /usr/local/bin/duplicacy; sudo chmod +x /usr/local/bin/duplicacy

script:
  - make test
